### ISSUE TITLE
Readme.md git error

### ISSUE THREAD

**Issue by OriginalGoku** [NivC/SINBAD#1]
On the Readme file, 
under Getting Started
the git command:

`git clone https://github.com/eliahuhorwitz/Conffusion.git`

Is for cloning the Conffusion project.
This should be changed to 
`https://github.com/NivC/SINBAD.git`
and then the line after should be changed to SINBAD in all capital letters:
`cd SINBAD`

**Comment by NivC** [comment]
Good catch!
I will fix.

Thanks for letting me know,
Niv.
