### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by OriginalGoku** [NivC/SINBAD#2]
Running the requirements file generates the following warning: 
```
WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
Discarding https://files.pythonhosted.org/packages/17/76/47d0cc8161f4bf988583a2839bb1e56baf09d6b80cfa472b9eba4d5f543b/faiss-gpu-1.7.1.post2.tar.gz (from https://pypi.org/simple/faiss-gpu/): Requested faiss-cpu from https://files.pythonhosted.org/packages/17/76/47d0cc8161f4bf988583a2839bb1e56baf09d6b80cfa472b9eba4d5f543b/faiss-gpu-1.7.1.post2.tar.gz (from -r requirements.txt (line 3)) has inconsistent name: expected 'faiss-gpu', but metadata has 'faiss-cpu'
```

this can be resolved by using 
`faiss-cpu `
instead of `faiss-gpu`

Also i'd advise to list `numpy` as the first required package since I think wandb might require `numpy` as a required package.

**Comment by NivC** [comment]
Thanks. 
`faiss-gpu` actually worked for me, but it might be dependent on other environmental settings.

Anyhow, changing according to you suggestions.

Thanks again,
Niv.
