### ISSUE TITLE
Data Preparation typo

### ISSUE THREAD

**Issue by OriginalGoku** [NivC/SINBAD#3]
I assume the following line in the headline "Data Preparation" paragraph 1. is a typo:
`cd ../dataset_loco` `

the extra backtick character at the end of the line is to create a bquote prompt but I see no reason for this. 
so the proper code should be
`cd ../dataset_loco`
without the "`" at the end of the line

**Comment by NivC** [comment]
Fixed.

Thanks again!
Niv.
