### ISSUE TITLE
Is this the entire code for the logical anomaly detection on MVTec Loco?

### ISSUE THREAD

**Issue by liutongkun** [NivC/SINBAD#4]
Thank you for your outstanding work. Currently, is it the entire code or its just partial code?

**Comment by NivC** [comment]
Thanks for the kind compliments!

This part of the code calculate the anomaly score using a single label and a single crop (Sec. 5.3 in the paper). I hope to upload the code for ensmbeling the different crops/ResNet levels together soon. 

Niv.
