### ISSUE TITLE
wandb.errors

### ISSUE THREAD

**Issue by simplewy** [NivC/SINBAD#5]
when I run the script `python sinbad_single_layer.py --mvtype breakfast_box_loco  --pyramid_level 7` on PowerShell,  an error is reported: `wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)`.

**Comment by NivC** [comment]
Hi,

I use wandb only to log the results. You can just remove all of its usages.

Best,
Niv.
