### ISSUE TITLE
inference speed

### ISSUE THREAD

**Issue by yjszyd0813** [NivC/SINBAD#6]
Hello, I am interested in the content of this article. Please I would like to ask, how is the speed of inference of this method compared to EfficientAD?

**Comment by NivC** [comment]
Dear yjszyd0813,

This method can be easily accelerated to real-time if needed. Essentially, it extracts deep features, and applies random histograms to them. Any additional component (e.g., multi-resolution ensemble) has only a marginal effect on the accuracy, and can be performed only on samples suspected anomalous by a single resolution layer - see manuscript. Alternatively, the different resolutions/layers can run in parallel.

In any case, the published code here is aimed for research purposes, and is not concerned with such optimization.

As EfficientAD may also have its own optimizations and I am less familiar with that code, I rather not answer for it. I do want to mention that the two methods have complementary strengths; so I would advise you to try both for your use case, and figure out first which gives the best performance for you (or combine them). After that, I believe you could modify each one (or both) to run in real-time, if needed.

Best,
Niv.
